# Generated by Django 6.0 on 2026-05-18 07:12

from ctypes import cast
from typing import TYPE_CHECKING
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def default_settings_forward(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    FontConfig = apps.get_model("bd_fontchanger", "FontConfig")
    FontConfig.objects.get_or_create(pk=1, defaults={"name": "settings"})


def default_settings_backwards(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FontConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="global", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Font",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        help_text="The font file",
                        upload_to="",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["ttf", "otf"])],
                    ),
                ),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(1, "Title"), (2, "Ability Name"), (3, "Ability Desc"), (4, "Stats"), (5, "Credits")],
                        help_text="The type of font",
                        unique=True,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        help_text="The font size",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(400),
                        ],
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bd_fontchanger.fontconfig"),
                ),
            ],
        ),
        migrations.RunPython(default_settings_forward, default_settings_backwards),
    ]
